### ISSUE TITLE
Add chocobot to #chocolatey on FreeNode

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocobot-gitter#2]
https://github.com/nandub/hubot-irc - freenode #chocolatey IRC nick (chocobot)

**Comment by gep13** [comment]
@ferventcoder okay, I am going to hold my hands up and say that I have never used IRC before.  Is there something that I need to do in order to create the IRC end of this plugin?  Or can I just set up all those variables, and things will just start working?

**Comment by ferventcoder** [comment]
Here are the variables you will need:

```
heroku config:add HUBOT_IRC_SERVER="chat.freenode.net"
heroku config:add HUBOT_IRC_USESSL="true"
heroku config:add HUBOT_IRC_PORT=6697
heroku config:add HUBOT_IRC_ROOMS="#chocolatey"
heroku config:add HUBOT_IRC_NICK="chocobot"
heroku config:add HUBOT_IRC_UNFLOOD="true"
heroku config:add HUBOT_IRC_SERVER_FAKE_SSL="true"
heroku config:add HUBOT_IRC_PRIVATE="true"
```

I'll probably want to set up a nickserv account and get you those details privately.

**Comment by gep13** [comment]
@ferventcoder I have added all of the above configuration variables, so chocobot should now have everything it needs.  I just need to add the extension now.

**Comment by gep13** [comment]
@ferventcoder let me know how you get on with the IRC side of things, and whether this issue can be closed.

**Comment by ferventcoder** [comment]
So we have everything working except chocobot won't join the room for some odd reason. Can you turn off HUBOT_IRC_PRIVATE for now?

**Comment by ferventcoder** [comment]
And by turn off you need to set it to null, false will have the same effect (per the documentation of set it to anything).

**Comment by gep13** [comment]
Done, deploying now

**Comment by ferventcoder** [comment]
- https://github.com/pablasso/chocobot
- http://forum.swiftirc.net/viewtopic.php?f=26&t=4947
- https://github.com/Gotos/Chocobot 

Let's rename to `choco-bot` for IRC only. Leave the private thing unset.

**Comment by ferventcoder** [comment]
for IRC only that is

**Comment by ferventcoder** [comment]
still not quite right.

**Comment by ferventcoder** [comment]
Looks like we didn't actually join the network (based on that someone elses bot with same name).

**Comment by gep13** [comment]
:crying_cat_face: let me know if you have any other things you want me to try.

**Comment by ferventcoder** [comment]
Closed via https://github.com/chocolatey/chocobot-gitter/commit/e891ed1862768f23ce2e903cbcebf229b7413744 and https://github.com/chocolatey/chocobot-gitter/commit/30f0d1cc57fe83d5491feadb66f458f1139fb04e

**Comment by ferventcoder** [comment]
I've also set the HUBOT_ADAPTER variable to "gitter2" on the gitter heroku, so no worries on update.

**Comment by gep13** [comment]
Noice! :+1:
