### ISSUE TITLE
Fitbit Leaders

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocobot-gitter#4]
I quite like the idea of using this one:

https://github.com/hubot-scripts/hubot-fitbit-leaders

Need to figure out how to walk through this process once though:

https://dev.fitbit.com/apps/oauthtutorialpage

**Comment by ferventcoder** [comment]
Yes! We use that one as well. Chocobot needs a fitbit account I believe.

On Monday, January 26, 2015, Gary Ewan Park notifications@github.com
wrote:

> I quite like the idea of using this one:
> 
> https://github.com/hubot-scripts/hubot-fitbit-leaders
> 
> Need to figure out how to walk through this process once though:
> 
> https://dev.fitbit.com/apps/oauthtutorialpage
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chocolatey/chocobot-gitter/issues/4.

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by gep13** [comment]
Yip, I have set him up with an account, just need to get his oauth token sorted out. :-)

Sent from my Windows Phone

**Comment by gep13** [comment]
Used this tool:

https://www.runscope.com/oauth1_tool

To generate the oAuth token.  Thanks to @stephenyeargin for the pointer.

**Comment by gep13** [comment]
This seems to be working now, with the exception of the approve.  I will raise an issue about this, but for now, this is closed.

**Comment by gep13** [comment]
Issue raised here https://github.com/hubot-scripts/hubot-fitbit-leaders/issues/2
